namespace FrontToBackEnd.Domain.Constants;
internal static class HtmlTags
{
    // html tag constants
    private static readonly string _html = "html";
    private static readonly string _body = "body";
    private static readonly string _h1 = "h1";
    private static readonly string _h2 = "h2";
    private static readonly string _h3 = "h3";
    private static readonly string _h4 = "h4";
    private static readonly string _h5 = "h5";
    private static readonly string _h6 = "h6";
    private static readonly string _p = "p";
    private static readonly string _div = "div";
    private static readonly string _span = "span";
    private static readonly string _a = "a";
    private static readonly string _b = "b";
    private static readonly string _i = "i";
    private static readonly string _u = "u";
    private static readonly string _br = "br";
    private static readonly string _hr = "hr";
    private static readonly string _img = "img";
    private static readonly string _ul = "ul";
    private static readonly string _ol = "ol";
    private static readonly string _li = "li";
    private static readonly string _dl = "dl";
    private static readonly string _dt = "dt";
    private static readonly string _dd = "dd";
    private static readonly string _table = "table";
    private static readonly string _thead = "thead";
    private static readonly string _tbody = "tbody";
    private static readonly string _tfoot = "tfoot";
    private static readonly string _tr = "tr";
    private static readonly string _th = "th";
    private static readonly string _td = "td";
    private static readonly string _caption = "caption";
    private static readonly string _col = "col";
    private static readonly string _colgroup = "colgroup";
    private static readonly string _form = "form";
    private static readonly string _input = "input";
    private static readonly string _textarea = "textarea";
    private static readonly string _button = "button";
    private static readonly string _select = "select";
    private static readonly string _option = "option";
    private static readonly string _optgroup = "optgroup";
    private static readonly string _label = "label";
    private static readonly string _fieldset = "fieldset";
    private static readonly string _legend = "legend";
    private static readonly string _script = "script";
    private static readonly string _noscript = "noscript";
    private static readonly string _style = "style";
    private static readonly string _link = "link";
    private static readonly string _meta = "meta";
    private static readonly string _base = "base";
    private static readonly string _head = "head";
    private static readonly string _title = "title";
    private static readonly string _address = "address";
    private static readonly string _article = "article";
    private static readonly string _aside = "aside";
    private static readonly string _footer = "footer";
    private static readonly string _header = "header";

    public static (string open, string close) Html { get => GetTag(_html); }
    public static (string open, string close) Body { get => GetTag(_body); }
    public static (string open, string close) H1 { get => GetTag(_h1); }
    public static (string open, string close) H2 { get => GetTag(_h2); }
    public static (string open, string close) H3 { get => GetTag(_h3); }
    public static (string open, string close) H4 { get => GetTag(_h4); }
    public static (string open, string close) H5 { get => GetTag(_h5); }
    public static (string open, string close) H6 { get => GetTag(_h6); }
    public static (string open, string close) P { get => GetTag(_p); }
    public static (string open, string close) Div { get => GetTag(_div); }
    public static (string open, string close) Span { get => GetTag(_span); }
    public static (string open, string close) A { get => GetTag(_a); }
    public static (string open, string close) B { get => GetTag(_b); }
    public static (string open, string close) I { get => GetTag(_i); }
    public static (string open, string close) U { get => GetTag(_u); }
    public static (string open, string close) Br { get => GetTag(_br); }
    public static (string open, string close) Hr { get => GetTag(_hr); }
    public static (string open, string close) Img { get => GetTag(_img); }
    public static (string open, string close) Ul { get => GetTag(_ul); }
    public static (string open, string close) Ol { get => GetTag(_ol); }
    public static (string open, string close) Li { get => GetTag(_li); }
    public static (string open, string close) Dl { get => GetTag(_dl); }
    public static (string open, string close) Dt { get => GetTag(_dt); }
    public static (string open, string close) Dd { get => GetTag(_dd); }
    public static (string open, string close) Table { get => GetTag(_table); }
    public static (string open, string close) Thead { get => GetTag(_thead); }
    public static (string open, string close) Tbody { get => GetTag(_tbody); }
    public static (string open, string close) Tfoot { get => GetTag(_tfoot); }
    public static (string open, string close) Tr { get => GetTag(_tr); }
    public static (string open, string close) Th { get => GetTag(_th); }
    public static (string open, string close) Td { get => GetTag(_td); }
    public static (string open, string close) Caption { get => GetTag(_caption); }
    public static (string open, string close) Col { get => GetTag(_col); }
    public static (string open, string close) Colgroup { get => GetTag(_colgroup); }
    public static (string open, string close) Form { get => GetTag(_form); }
    public static (string open, string close) Input { get => GetTag(_input); }
    public static (string open, string close) Textarea { get => GetTag(_textarea); }
    public static (string open, string close) Button { get => GetTag(_button); }
    public static (string open, string close) Select { get => GetTag(_select); }
    public static (string open, string close) Option { get => GetTag(_option); }
    public static (string open, string close) Optgroup { get => GetTag(_optgroup); }
    public static (string open, string close) Label { get => GetTag(_label); }
    public static (string open, string close) Fieldset { get => GetTag(_fieldset); }
    public static (string open, string close) Legend { get => GetTag(_legend); }
    public static (string open, string close) Script { get => GetTag(_script); }
    public static (string open, string close) Noscript { get => GetTag(_noscript); }
    public static (string open, string close) Style { get => GetTag(_style); }
    public static (string open, string close) Link { get => GetTag(_link); }
    public static (string open, string close) Meta { get => GetTag(_meta); }
    public static (string open, string close) Base { get => GetTag(_base); }
    public static (string open, string close) Head { get => GetTag(_head); }
    public static (string open, string close) Title { get => GetTag(_title); }
    public static (string open, string close) Address { get => GetTag(_address); }
    public static (string open, string close) Article { get => GetTag(_article); }
    public static (string open, string close) Aside { get => GetTag(_aside); }
    public static (string open, string close) Footer { get => GetTag(_footer); }
    public static (string open, string close) Header { get => GetTag(_header); }

    private static (string open, string close) GetTag(string tag)
        => ($"<{tag}>", $"</{tag}>");
}
